### ISSUE TITLE
Multiple versions does not work

### ISSUE THREAD

**Issue by HadiSDev** [BendingSpoons/poetry-private-repo-plugin#4]
I tried to build this on a mac but instead of installing torch-2.0.0 it installs torch-2.0.0+cpu. It makes sense because the plugin forces everything with torch to use that source but there must be a way to change the behavior to work with this case

```
torch = [
            { version = "2.0.0+cpu", source = "torchcpu", markers = "sys_platform != 'darwin'"},
            { version = "2.0.0", markers = "sys_platform == 'darwin'"}
        ]
[tool.poetry-private-repo-plugin.enforce-source]
"torch-*" = "torchcpu"

[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true
```

**Comment by ralbertazzi** [comment]
Hi @HadiSDev, have you tried this?
1. Define two secondary sources, like `torchcpu` and `torchgpu` (pointing to two different urls).
2. Assign explicitly the correct source to each of torch
3. Remove the `tool.poetry-private-repo-plugin.enforce-source` setting

**Comment by ralbertazzi** [comment]
Closing as you can now better handle it in Poetry 1.5 and you can we'll dismiss this plugin. Check the conversations in https://github.com/python-poetry/poetry/issues/6409
